Demo_GiaoDien/Models/ErrorViewModel.cs
namespace Demo_GiaoDien.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo_GiaoDien/Areas/Admin/Controllers/AdmController.cs
using Microsoft.AspNetCore.Mvc;

namespace Demo_GiaoDien.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdmController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Demo_GiaoDien/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Demo_GiaoDien.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Cart()
        {
            return View();
        }
        public IActionResult CheckOut()
        {
            return View();
        }
        public IActionResult EditMyAccount()
        {
            return View();
        }
        public IActionResult Home()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MyAccount()
        {
            return View();
        }
        public IActionResult MyAddress()
        {
            return View();
        }
        public IActionResult MyOder()
        {
            return View();
        }
        public IActionResult MyProfile()
        {
            return View();
        }
        public IActionResult OrderHistory()
        {
            return View();
        }
        public IActionResult ProductDetail()
        {
            return View();
        }
        public IActionResult ShowListProduct()
        {
            return View();
        }
        public IActionResult SignIn()
        {
            return View();
        }
        public IActionResult SignUp()
        {
            return View();
        }

    }
}

Demo_GiaoDien/Areas/Admin/Views/Adm/Index.cshtml
index admin

Demo_GiaoDien/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <br />
        <br />
        Xin chào đây là giao diện layout admin
        <br />
        <br />
        <a asp-area="" asp-controller="Home" asp-action="Home">Về Home User</a>
        <hr />
        <hr />
        <br />
        <br />
        @RenderBody()
    </div>
</body>
</html>

Demo_GiaoDien/Views/Home/Cart.cshtml
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<main class="col-md-9">
<div class="card">

<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
<tr>
	<td>
		<figure class="itemside">
			<div class="aside"><img src="~/images/items/1.jpg" class="img-sm"></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">Some name of item goes here nice</a>
				<p class="text-muted small">Size: XL, Color: blue, <br> Brand: Gucci</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<select class="form-control">
			<option>1</option>
			<option>2</option>	
			<option>3</option>	
			<option>4</option>	
		</select> 
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$1156.00</var> 
			<small class="text-muted"> $315.20 each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a> 
	<a href="" class="btn btn-light"> Remove</a>
	</td>
</tr>
<tr>
	<td>
		<figure class="itemside">
			<div class="aside"><img src="~/images/items/2.jpg" class="img-sm"></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">Product name  goes here nice</a>
				<p class="text-muted small">Size: XL, Color: blue, <br> Brand: Gucci</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<select class="form-control">
			<option>1</option>
			<option>2</option>	
			<option>3</option>	
			<option>4</option>	
		</select> 
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$149.97</var> 
			<small  class="text-muted"> $75.00 each </small>  
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a> 
	<a href="" class="btn btn-light btn-round"> Remove</a>
	</td>
</tr>
<tr>
	<td>
		<figure class="itemside">
			<div class="aside"><img src="~/images/items/3.jpg" class="img-sm"></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">Another name of some product goes just here as a demo text </a>
				<p class="small text-muted">Size: XL, Color: blue,  Brand: Tissot</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<select class="form-control">
			<option>1</option>
			<option>2</option>	
			<option>3</option>	
		</select> 
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$98.00</var> 
			<small class="text-muted"> $578.00 each</small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
		<a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a> 
		<a href="" class="btn btn-light btn-round"> Remove</a>
	</td>
</tr>
</tbody>
</table>

<div class="card-body border-top">
	<a href="#" class="btn btn-primary float-md-right"> Make Purchase <i class="fa fa-chevron-right"></i> </a>
	<a href="#" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
</div>	
</div> <!-- card.// -->

<div class="alert alert-success mt-3">
	<p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
</div>

	</main> <!-- col.// -->
	<aside class="col-md-3">
		<div class="card mb-3">
			<div class="card-body">
			<form>
				<div class="form-group">
					<label>Have coupon?</label>
					<div class="input-group">
						<input type="text" class="form-control" name="" placeholder="Coupon code">
						<span class="input-group-append"> 
							<button class="btn btn-primary">Apply</button>
						</span>
					</div>
				</div>
			</form>
			</div> <!-- card-body.// -->
		</div>  <!-- card .// -->
		<div class="card">
			<div class="card-body">
					<dl class="dlist-align">
					  <dt>Total price:</dt>
					  <dd class="text-right">USD 568</dd>
					</dl>
					<dl class="dlist-align">
					  <dt>Discount:</dt>
					  <dd class="text-right">USD 658</dd>
					</dl>
					<dl class="dlist-align">
					  <dt>Total:</dt>
					  <dd class="text-right  h5"><strong>$1,650</strong></dd>
					</dl>
					<hr>
					<p class="text-center mb-3">
						<img src="~/images/misc/payments.png" height="26">
					</p>
					
			</div> <!-- card-body.// -->
		</div>  <!-- card .// -->
	</aside> <!-- col.// -->
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

Demo_GiaoDien/Views/Home/CheckOut.cshtml
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container" style="max-width: 720px;">

<div class="card mb-4">
      <div class="card-body">
      <h4 class="card-title mb-3">Delivery info</h4>

	  <div class="form-row">
			<div class="form-group col-sm-6">
				<label class="js-check box active">
					<input type="radio" name="dostavka" value="option1" checked>
					<h6 class="title">Standart delivery</h6>
					<p class="text-muted">Free by airline within 20 days</p>
				</label> <!-- js-check.// -->
			</div>
			<div class="form-group col-sm-6">
				<label class="js-check box">
					<input type="radio" name="dostavka" value="option1">
					<h6 class="title">Fast delivery</h6>
					<p class="text-muted">Extra 20$ will be charged </p>
				</label> <!-- js-check.// -->
			</div>
		</div> <!-- form row.// -->

	<div class="form-row">
		<div class="col form-group">
			<label>First name</label>
		  	<input type="text" class="form-control" placeholder="">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>Last name</label>
		  	<input type="text" class="form-control" placeholder="">
		</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->

	<div class="form-row">
		<div class="col form-group">
			<label>Email</label>
		  	<input type="email" class="form-control" placeholder="">
		</div> <!-- form-group end.// -->
		<div class="col form-group">
			<label>Phone</label>
		  	<input type="text" class="form-control" placeholder="">
		</div> <!-- form-group end.// -->
	</div> <!-- form-row end.// -->

	<div class="form-row">
		<div class="form-group col-md-6">
		  <label>Country</label>
		  <select id="inputState" class="form-control">
		    <option> Choose...</option>
		      <option>Uzbekistan</option>
		      <option>Russia</option>
		      <option selected="">United States</option>
		      <option>India</option>
		      <option>Afganistan</option>
		  </select>
		</div> <!-- form-group end.// -->
		<div class="form-group col-md-6">
		  <label>City</label>
		  <input type="text" class="form-control">
		</div> <!-- form-group end.// -->
	</div> <!-- form-row.// -->
	<div class="form-group">
		<label>Adress</label>
       <textarea class="form-control" rows="2"></textarea>
    </div> <!-- form-group// -->  

      </div> <!-- card-body.// -->
    </div>  <!-- card .// -->


		<div class="card mb-4">
      <div class="card-body">
      <h4 class="card-title mb-4">Payment</h4>
      <form role="form" style="max-width:380px;">
			<div class="form-group">
			<label for="username">Name on card</label>
			<input type="text" class="form-control" name="username" placeholder="Ex. John Smith" required="">
			</div> <!-- form-group.// -->

			<div class="form-group">
			<label for="cardNumber">Card number</label>
			<div class="input-group">
				<input type="text" class="form-control" name="cardNumber" placeholder="">
				<div class="input-group-append">
					<span class="input-group-text">
						<i class="fab fa-cc-visa"></i> &nbsp; <i class="fab fa-cc-amex"></i> &nbsp; 
						<i class="fab fa-cc-mastercard"></i> 
					</span>
				</div>
			</div> <!-- input-group.// -->
			</div> <!-- form-group.// -->

			<div class="row">
				<div class="col-md flex-grow-0">
					<div class="form-group">
						<label class="hidden-xs">Expiration</label>
						<div class="form-inline" style="min-width: 220px">
							<select class="form-control" style="width:100px">
								<option>MM</option>
								<option>01 - Janiary</option>
								<option>02 - February</option>
								<option>03 - February</option>
							</select>
							<span style="width:20px; text-align: center"> / </span>
							<select class="form-control" style="width:100px">
								<option>YY</option>
								<option>2018</option>
								<option>2019</option>
							</select>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group">
						<label data-toggle="tooltip" title="3 digits code on back side of the card">CVV <i class="fa fa-question-circle"></i></label>
						<input class="form-control" required="" type="text">
					</div> <!-- form-group.// -->
				</div>
			</div> <!-- row.// -->
			<button class="subscribe btn btn-primary btn-block" type="button"> Confirm  </button>
		</form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->


<br><br> 

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

Demo_GiaoDien/Views/Home/EditMyAccount.cshtml
@{
Layout = null;
}


<div class="row">
    <div class="col-md">
        <img id="previewImage"  src="~/images/avatars/avatar3.jpg" class="img-md rounded-circle border">
        <br />
        <div class="col-md">
            <input type="file" id="imageInput" accept="image/*" class="btn-link">
        </div>
    </div>

</div>
<br><br><br><br><br><br>
<div class="card">
    <div class="card-body">
        <form class="row">
            <div class="col-md-9">
                <div class="form-row">
                    <div class="col form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" value="Vosidiy">
                    </div>
                    <!-- form-group end.// -->
                    <div class="col form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" value="vosidiy@gmail.com">
                    </div>
                    <!-- form-group end.// -->
                </div>
                <!-- form-row.// -->

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Country</label>
                        <select id="inputState" class="form-control">
                            <option>Choose...</option>
                            <option>Uzbekistan</option>
                            <option>Russia</option>
                            <option selected="">United States</option>
                            <option>India</option>
                            <option>Afghanistan</option>
                        </select>
                    </div>
                    <!-- form-group end.// -->
                    <div class="form-group col-md-6">
                        <label>City</label>
                        <input type="text" class="form-control">
                    </div>
                    <!-- form-group end.// -->
                </div>
                <!-- form-row.// -->

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Zip</label>
                        <input type="text" class="form-control" value="123009">
                    </div>
                    <!-- form-group end.// -->
                    <div class="form-group col-md-6">
                        <label>Phone</label>
                        <input type="text" class="form-control" value="+123456789">
                    </div>
                    <!-- form-group end.// -->
                </div>
                <!-- form-row.// -->

                <button class="btn btn-primary">Save</button>
                <button class="btn btn-light">Change password</button>



            </div> <!-- col-md-9 -->
        </form>
    </div> <!-- card-body -->
</div> <!-- card -->

Demo_GiaoDien/Views/Home/Home.cshtml
Đây là home

Demo_GiaoDien/Views/Home/MyAccount.cshtml
<div id="setting-content">
    <h1>My Account</h1>
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">
            <div class="row">
                <aside class="col-md-3">
                    <nav class="list-group">
                        <partial name="_partialAccount" />
                    </nav>
                </aside> <!-- col.// -->
                <main class="col-md-9">
                    <article class="card mb-3">
                        <div class="card-body">
                            <div id="page-content">

                            </div>
                        </div> <!-- card-body .// -->
                    </article> <!-- card.// -->
                </main> <!-- col.// -->
            </div>

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
</div>

Demo_GiaoDien/Views/Home/MyAddress.cshtml
@{
Layout = null;
}
<main class="col-md-9">

    <a href="#" class="btn btn-light mb-3"> <i class="fa fa-plus"></i> Add new address </a>

    <div class="row">
        <div class="col-md-6">
            <article class="box mb-4">
                <h6>London, United Kingdom</h6>
                <p>Building: Nestone <br> Floor: 22, Aprt: 12 </p>
                <a href="#" class="btn btn-light disabled"> <i class="fa fa-check"></i> Default</a> <a href="#"
                    class="btn btn-light"> <i class="fa fa-pen"></i> </a> <a href="#" class="btn btn-light"> <i
                        class="text-danger fa fa-trash"></i> </a>
            </article>
        </div> <!-- col.// -->
        <div class="col-md-6">
            <article class="box mb-4">
                <h6>Tashkent, Uzbekistan</h6>
                <p>Building one <br> Floor: 2, Aprt: 32 </p>
                <a href="#" class="btn btn-light">Make default</a> <a href="#" class="btn btn-light"> <i
                        class="fa fa-pen"></i> </a> <a href="#" class="btn btn-light"> <i
                        class="text-danger fa fa-trash"></i> </a>
            </article>
        </div> <!-- col.// -->
    </div> <!-- row.// -->

</main> <!-- col.// -->

Demo_GiaoDien/Views/Home/MyOrder.cshtml
<article class="card-group card-stat">
    <a class="card bg" href="#" onclick="loadPageWithParams('controller', 'action', 'param1')">
        <div class="p-2">
            <h4 class="title">38</h4>
            <span>Chờ xác nhận</span>
        </div>
    </a>
    <a class="card bg" href="#" onclick="loadPageWithParams('controller', 'action', 'param1')">
        <div class="p-2">
            <h4 class="title">38</h4>
            <span>Chờ lấy hàng</span>
        </div>
    </a>
    <a class="card bg" href="#" onclick="loadPageWithParams('controller', 'action', 'param1')">
        <div class="p-2">
            <h4 class="title">38</h4>
            <span>Đang giao</span>
        </div>
    </a>
    <a class="card bg" href="#" onclick="loadPageWithParams('controller', 'action', 'param1')">
        <div class="p-2">
            <h4 class="title">38</h4>
            <span>Đã nhận</span>
        </div>
    </a>
    <a class="card bg" href="#" onclick="loadPageWithParams('controller', 'action', 'param1')">
        <div class="p-2">
            <h4 class="title">38</h4>
            <span>Đã hủy</span>
        </div>
    </a>
    <a class="card bg" onclick="loadPageWithParams('controller', 'action', 'param1')">
        <div class="p-2">
            <h4 class="title">38</h4>
            <span>Trả hàng</span>
        </div>
    </a>

</article>
<div id="page-content"> @*load data vào đây*@

</div>
<script>
    function loadPageWithParams(controller, action, param1) {
        // Sử dụng Ajax để tải nội dung trang con với tham số truyền vào
        $.ajax({
            url: '/' + controller + '/' + action,
            type: 'GET',
            data: {
                param1: param1,
            },
            success: function (result) {
                // Gán nội dung trang con vào div page-content
                $('#page-content').html(result);
            }
        });
    }
</script>

Demo_GiaoDien/Views/Home/MyProfile.cshtml
@{
Layout = null;
}
<figure class="icontext">
    <div class="icon">
        <img class="rounded-circle img-sm border" src="~/images/avatars/avatar3.jpg">
    </div>
    <div class="text">
        <strong> My name </strong> <br>
        <p class="mb-2"> myloginname@gmail.com </p>
        <a href="" class="btn btn-light btn-sm"  onclick="loadPage('Home', 'EditMyAccount')">Edit</a>
    </div>
</figure>
<hr>
<p>
    <i class="fa fa-map-marker text-muted"></i> &nbsp; My address:
    <br>
    Tashkent city, Street name, Building 123, House 321 &nbsp
    <a href="#" class="btn-link"> Edit</a>
</p>
<hr>
<p>
 &nbsp; Dịch vụ ngoài:
    <br>
    Google:&nbsp demo@ff.ff
     &nbsp &nbsp &nbsp &nbsp;
    <a href="#" class="btn-link"> Hủy kết nối</a>
</p>

Demo_GiaoDien/Views/Home/OrderHistory.cshtml
hiện bill + click thì hiện detail

Demo_GiaoDien/Views/Home/SignIn.cshtml
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-conten padding-y">

        <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 700px; max-height: 1000px;">
            <div class="card-body">
                <h4 class="card-title mb-4">Sign in</h4>
                <form>
                    <a href="#" class="btn btn-facebook btn-block mb-4"> <i class="fab fa-facebook-f"></i> &nbsp Sign in
                        with Facebook</a>
                    <a href="#" class="btn btn-google btn-block mb-4"> <i class="fab fa-google"></i> &nbsp Sign in with
                        Google</a>
                    <div class="form-group">
                        <input name="" class="form-control" placeholder="Username" type="text">
                    </div> <!-- form-group// -->
                    <div class="form-group">
                        <input name="" class="form-control" placeholder="Password" type="password">
                    </div> <!-- form-group// -->

                    <div class="form-group">
                        <a href="#" class="float-right">Forgot password?</a>
                        <label class="float-left custom-control custom-checkbox"> <input type="checkbox"
                                class="custom-control-input" checked="">
                            <div class="custom-control-label"> Remember </div>
                        </label>
                    </div> <!-- form-group form-check .// -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Login </button>
                    </div> <!-- form-group// -->
                </form>
            </div> <!-- card-body.// -->
        </div> <!-- card .// -->

        <p class="text-center mt-4">Don't have account? <a href="#">Sign up</a></p>
        <br><br>
        <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

Demo_GiaoDien/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link rel="shortcut icon" href="~/images/logo.png" >

    <!-- jQuery -->
    <script src="~/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="~/js/script.js" type="text/javascript"></script>
    <!-- bootraps<!-->
    <link rel="stylesheet" href="~//lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~//css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~//Demo_GiaoDien.styles.css" asp-append-version="true" />
</head>

<body>
    <header class="section-header">
        <div class="container">
            <section class="header-main border-bottom">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-3 col-md-12">
                            <a  class="brand-wrap">
                                <img class="logo" style="width:250px;height:auto" src="~/images/4man.png">
                            </a> <!-- brand-wrap.// -->
                        </div>
                        <div class="col-xl-6 col-lg-5 col-md-6">
                            <form action="#" class="search-header">
                                <div class="input-group w-100">
                                    <select class="custom-select border-right" name="category_name">
                                        <option value="">All type</option>
                                        <option value="codex">Special</option>
                                        <option value="comments">Only best</option>
                                        <option value="content">Latest</option>
                                    </select>
                                    <input type="text" class="form-control" placeholder="Search">

                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">
                                            <i class="fa fa-search"></i> Search
                                        </button>
                                    </div>
                                </div>
                            </form> <!-- search-wrap .end// -->
                        </div> <!-- col.// -->
                        <div class="col-xl-4 col-lg-4 col-md-6">
                            <div class="widgets-wrap float-md-right">
                                <div class="widget-header">
                                    <a class="widget-view" asp-controller="Home" asp-action="Cart">
                                        <div class="icon-area">
                                            <i class="fa fa-shopping-cart"></i>
                                            <span class="notify">3</span>
                                        </div>
                                        <small class="text"> Cart </small>
                                    </a>
                                </div>
                                <div class="widget-header mr-3">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                                        <img src="~/images/avatars/logo.png"
                                            class="rounded-circle" height="25" alt="Black and White Portrait of a Man"
                                            loading="lazy" />
                                    </a>
                                    <ul class="dropdown-menu small">
                                        <li>
                                            <a class="dropdown-item" asp-controller="Home" asp-action="MyAccount">  <i class="fa fa-user" aria-hidden="true"></i> My Account</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="Home" asp-action="MyOrder"> <i class="fa fa-shopping-cart" aria-hidden="true"></i> My Order</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="Home" asp-action="OrderHistory">  <i class="fa fa-id-card-o" aria-hidden="true"></i>Order History</a>
                                        </li>

                                        <li>
                                            <a class="dropdown-item" href="#"> <i class="fa fa-sign-out"></i> Log Out</a>
                                        </li>
                                        
                                    </ul>
                                </div>
                            </div> <!-- widgets-wrap.// -->
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->
                </div> <!-- container.// -->
            </section> <!-- header-main .// -->
            <nav class="navbar navbar-main navbar-expand pl-0">
                <ul class="navbar-nav flex-wrap">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Admin" asp-controller="Adm" asp-action="Index">Admin</a>
                    </li><li class="nav-item">
                        <a class="nav-link"  asp-controller="Home" asp-action="Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="ShowListProduct">ShowListProduct</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="ProductDetail">ProductDetail</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="SignIn">SignIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="SignUp">SignUp</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> Dropdown </a>
                        <div class="dropdown-menu small">
                            <nav class="row">
                                <div class="col-md-auto">
                                    <a class="nav-link" asp-controller="Home" asp-action="CheckOut">CheckOut</a>
                                </div>
                                <div class="col-md-auto">
                                    <a class="nav-link" asp-controller="Home" asp-action="ShowListProduct">ShowListProduct</a>
                                </div>

                            </nav> <!--  row end .// -->
                        </div> <!--  dropdown-menu dropdown-large end.// -->
                    </li>
                </ul>
            </nav> <!-- navbar-main  .// -->

        </div> <!-- container.// -->
    </header> <!-- section-header.// -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Demo_GiaoDien
        </div>
    </footer>
    <script src="~//lib/jquery/dist/jquery.min.js"></script>
    <script src="~//lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~//js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>